version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresDB:/data/postgres
    env_file:
      - ./server/.env
  
  node-express-api:
    stdin_open: true
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: node-express-api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: always
volumes:
  postgresDB:
